error_sensors: # Keep empty if you do not have any/modify pins as needed
  - pin: 22
    name: Saltwater
    trigger_when: exposed
    permitted_runs: 3
  - pin: 19
    name: RODI
    trigger_when: exposed
    permitted_runs: 3
  - pin: 23
    name: Wastewater
    trigger_when: submerged
    permitted_runs: 0
tank_sensors: # Put appropriate pins and/or change sensors as needed
  - pin: 5
    name: Normal Level
    when_submerged: [full]
    when_exposed: [low, draining]
  - pin: 6
    name: Low Level
    when_submerged: [full, draining]
    when_exposed: [low]
pumps: # Put in the correct BCM pin #s and whether your relays are active high or low
  - name: Wastewater Pump
    pin: 21
    active_high: False
  - name: Saltwater Pump
    pin: 26
    active_high: False
  - name: RODI Pump
    pin: 20
    active_high: False
messenger: # You need to enter the correct details here... This is an example
    email_address: ##### PUT AN EMAIL IN
    password: ##### PUT A PASSWORD IN; RECCOMEND AN APP PASSWORD IF PLAINTEXT
    contacts:
      name: ##### YOU CAN USE AN REGULAR EMAIL OR TEXTING ADDRESS (LOOKUP PHONE PROVIDER)
    smtp_domain: ##### I.E. smpt.gmail.com
    imap_domain: ##### I.E. imap.gmail.com
    smtp_port: 465
    imap_port: 993
routine_updates:
  interval: 24
  unit: hours
routines:
  #Parameters for water changes/top offs, time units are in seconds.
  - name: Water Change
    interval: 16 # Whole numbers only
    unit: hours # Allowed: seconds, minutes, days, weeks, years
    priority: 2 # Generally, top off before changing water
    error_contacts: [Neil, Austin]
    completion_contacts: [Neil, Austin]
    run_time_confidence: .95
    steps: # An ordered list of the steps to take
    - name: Drain Tank # Step name
      start_state: full # Tank state to initiate this step on
      end_state: low # Tank state to end this step on
      pump: Wastewater Pump
      error_checks: [Saltwater, Wastewater]
      proceed_on_invalid_start: True
      proceed_on_timeout: True
      proceed_on_error: False
      cancel_on_critical_failure: False
    - name: Refill Tank
      start_state: low
      end_state: full
      pump: Saltwater Pump
      error_checks: [Saltwater, Wastewater]
      proceed_on_invalid_start: True
      proceed_on_timeout: True
  - name: Top Off
    interval: 5
    unit: minutes
    priority: 1
    error_contacts: [Neil, Austin]
    completion_contacts: []
    run_time_confidence: .98
    steps: # An ordered list of the steps to take
    - name: Refill
      start_state: draining
      end_state: full
      pump: RODI Pump
      error_checks: [RODI]
      report_invalid_start: False
      proceed_on_invalid_start: True
      proceed_on_timeout: True
