settings:
  dispenser:
    bounce_time: 5
  messenger:
    check_delay_sec: 30
    contacts:
      # Any valid apprise service addresses
      # See: https://github.com/caronc/apprise?tab=readme-ov-file#supported-notifications
      - !Contact
        name: name1
        address: pover://{user}@{token} # Ex sign-up for Pushover and set-up a user key and app token
    receivers:
      - !EmailReader # Right now, only email is available
        email_address: !Env "PIPYAWC_EMAIL"
        password: !Env "PIPYAWC_PWD"
        imap_domain: imap.gmail.com # For instance
        imap_port: 993

error_sensors:
  - pin: 21 #White cable
    name: Saltwater
    trigger_when: exposed
    permitted_runs: 1
#  - pin: 5 # Yellow
#    name: RODI
#    trigger_when: exposed
#    permitted_runs: 10

tank_sensors:
  - pin: 26 # Blue
    name: Normal Level
    when_submerged: [full]
    when_exposed: [low, draining]
  - pin: 20 # Orange
    name: Low Level
    when_submerged: [full, draining]
    when_exposed: [low]

pumps:
  - name: Wastewater Pump
    pin: 13 # 1
    active_high: True
  - name: Saltwater Pump
    pin: 16 # 3
    active_high: True
  - name: RODI Pump
    pin: 19 # 2
    active_high: True

routines:
  - name: Water-Change
    interval: 21
    unit: hours
    priority: 1
    error_contacts: []
    completion_contacts: []
    steps:
      - name: Top Off
        start_states: [draining]
        end_states: [full]
        pump: RODI Pump
        error_checks: [] #[Saltwater]
        proceed_on_invalid_start: True
        proceed_on_timeout: False
        proceed_on_error: False
        cancel_on_critical_failure: False
        max_runtime: 15
      - name: Drain Tank
        start_states: [full]
        end_states: [low]
        pump: Wastewater Pump
        error_checks: [] #[Saltwater]
        proceed_on_invalid_start: False
        proceed_on_timeout: True
        proceed_on_error: True
        cancel_on_critical_failure: False
        max_runtime: 900
      - name: Refill Tank
        start_states: [low, draining]
        end_states: [full]
        pump: Saltwater Pump
        error_checks: [] #[Saltwater, Wastewater]
        proceed_on_invalid_start: True
        proceed_on_timeout: True
        max_runtime: 1000
  - name: Top-Off
    interval: 1
    unit: minutes
    priority: 2
    error_contacts: []
    completion_contacts: []
    steps:
      - name: Refill
        start_states: [draining, low]
        end_states: [full]
        pump: RODI Pump
        error_checks: [] #[RODI]
        report_invalid_start: False
        proceed_on_invalid_start: True
        proceed_on_timeout: True
        max_runtime: 300
  - name: Salt-Refill
    interval: null
    unit: null
    priority: 0
    error_contacts: [Neil]
    completion_contacts: [Neil]
    steps:
      - name: Refill Salt
        start_states: [draining, low]
        end_states: [full]
        pump: Saltwater Pump
        error_checks: [] #[Saltwater]
        report_invalid_start: True
        proceed_on_invalid_start: True
        proceed_on_timeout: True
        max_runtime: 600
  - name: Low Top-Off
    interval: null
    unit: null
    priority: 0
    error_contacts: [Neil]
    completion_contacts: []
    steps:
      - name: Refill
        start_states: [low]
        end_states: [draining]
        pump: RODI Pump
        error_checks: [] #[RODI]
        report_invalid_start: False
        proceed_on_invalid_start: True
        proceed_on_timeout: True
        max_runtime: 300
